FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-worker.txt .
RUN pip install --no-cache-dir -r requirements-worker.txt

COPY src ./src
COPY chroma_db ./chroma_db

CMD ["python", "src/worker.py"]
